title: .NET VS Code Docker Debugging Settings
description: An opinionated approach to developing applications with VS Code and docker-compose. Designed for quick startup.
theme: jekyll-theme-slate
show_downloads: false
google_analytics: UA-191502149-1
