# Copyright 2020, Pave Aljinovic and Boran Car
# SPDX-License-Identifier: MIT

version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.release
        stdin_open: true
        tty: true
