FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS sdk
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS runtime
WORKDIR /app
COPY --from=sdk /app/out .

ENV DOTNET_ENVIRONMENT=Production
ENTRYPOINT ["dotnet", "Example.dll"]
